# spring.datasource.url=jdbc:mysql://docker-mysql:3306/mydb
spring.datasource.url=jdbc:mysql://docker-mysql:3306/mydb
spring.datasource.username=root
spring.datasource.password=test1234

server.port=9090

couponService.url=http://coupon-app:9091/couponapi/coupons/

#//
#
#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.port=9091

# ===================================================================
# JPA / HIBERNATE CONFIGURATION
# ===================================================================
# Specifies the database platform variant
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Controls the DDL validation and generation strategy
# Options: update, create, create-drop, validate, none
spring.jpa.hibernate.ddl-auto=update

# Enable this to see executed SQL queries in your console (useful for development)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true