spring.application.name=email-notification-service
server.port=9098

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wadatkarnikhil22@gmail.com
spring.mail.password=bmln upov ltgy vpbe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.starttls.enable=true


# mail.host=smtp.gmail.com
# mail.port=587
# mail.username=ankur.wadatkar@gmail.com
# mail.password=Ankur@4693
# mail.transport.protocol=smtp
# mail.smtp.auth=true
# mail.smtp.starttls.enable=true
# mail.from.email=<gmail-username@gmail.com>