spring.application.name=Spring-AI-ChatBot
server.port=8083
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0.8

# Logging Configuration
logging.level.root=INFO
logging.level.com.mco.springai=DEBUG
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n


spring.ai.openai.api-key=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

##Vector DB related properties
#spring.docker.compose.stop.command=down
#spring.ai.vectorstore.qdrant.initialize-schema=true
#spring.ai.vectorstore.qdrant.host=localhost
#spring.ai.vectorstore.qdrant.port=6334
#spring.ai.vectorstore.qdrant.collection-name=eazybytes