spring.application.name=order-service

server.port=8081

# H2
spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#####################========circuit breaker configurations========#####################
#========================================================================================
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-type=COUNT_BASED

# Number of calls that Circuit Breaker monitors in the sliding window.
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-size=10

# Circuit opens when the failure rate reaches 50% or more.
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failure-rate-threshold=50

# After the circuit opens, wait 10 seconds before moving to HALF_OPEN.
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.wait-duration-in-open-state=10s

# In HALF_OPEN state, allow 3 test calls to check whether Inventory Service has recovered.
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.permitted-number-of-calls-in-half-open-state=3

# Circuit Breaker needs at least 5 calls before it starts calculating the failure rate.
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.minimum-number-of-calls=5