-- ============================================================
-- SQL INTERVIEW PRACTICE DATABASE
-- PostgreSQL Version
-- ============================================================

-- Optional: create a schema
-- CREATE SCHEMA sql_practice;
-- SET search_path TO sql_practice;


-- ============================================================
-- 1. DEPARTMENT
-- ============================================================

DROP TABLE IF EXISTS employee_project CASCADE;
DROP TABLE IF EXISTS order_item CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS project CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS department CASCADE;


CREATE TABLE department (
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(50) NOT NULL,
    location VARCHAR(50)
);


INSERT INTO department (department_name, location)
VALUES
('IT', 'Pune'),
('HR', 'Mumbai'),
('Finance', 'Bangalore'),
('Sales', 'Delhi'),
('Marketing', 'Hyderabad'),
('Operations', 'Chennai'),
('Legal', 'Mumbai'),
('Research', 'Pune');


-- ============================================================
-- 2. EMPLOYEE
-- ============================================================

CREATE TABLE employee (
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    gender VARCHAR(10),
    salary DECIMAL(12,2),
    hire_date DATE,
    designation VARCHAR(50),
    department_id INT,
    manager_id INT,
    city VARCHAR(50),
    status VARCHAR(20),

    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id),

    CONSTRAINT fk_employee_manager
        FOREIGN KEY (manager_id)
        REFERENCES employee(employee_id)
);


INSERT INTO employee
(first_name, last_name, email, gender, salary, hire_date,
 designation, department_id, manager_id, city, status)
VALUES
('Amit', 'Sharma', 'amit@gmail.com', 'Male', 85000,
 '2019-01-15', 'Senior Developer', 1, NULL, 'Pune', 'ACTIVE'),

('Rahul', 'Patil', 'rahul@gmail.com', 'Male', 65000,
 '2021-03-10', 'Developer', 1, 1, 'Pune', 'ACTIVE'),

('Priya', 'Deshmukh', 'priya@gmail.com', 'Female', 95000,
 '2018-07-20', 'Tech Lead', 1, 1, 'Pune', 'ACTIVE'),

('Sneha', 'Kulkarni', 'sneha@gmail.com', 'Female', 55000,
 '2022-06-11', 'Developer', 1, 3, 'Mumbai', 'ACTIVE'),

('Rohit', 'Joshi', 'rohit@gmail.com', 'Male', 45000,
 '2023-01-05', 'Junior Developer', 1, 3, 'Pune', 'ACTIVE'),

('Neha', 'Shah', 'neha@gmail.com', 'Female', 75000,
 '2020-02-15', 'HR Manager', 2, NULL, 'Mumbai', 'ACTIVE'),

('Karan', 'Mehta', 'karan@gmail.com', 'Male', 50000,
 '2022-08-10', 'HR Executive', 2, 6, 'Mumbai', 'ACTIVE'),

('Pooja', 'Verma', 'pooja@gmail.com', 'Female', 48000,
 '2023-04-12', 'HR Executive', 2, 6, 'Mumbai', 'ACTIVE'),

('Vikas', 'Gupta', 'vikas@gmail.com', 'Male', 110000,
 '2017-05-18', 'Finance Manager', 3, NULL, 'Bangalore', 'ACTIVE'),

('Anjali', 'Singh', 'anjali@gmail.com', 'Female', 70000,
 '2020-09-25', 'Financial Analyst', 3, 9, 'Bangalore', 'ACTIVE'),

('Suresh', 'Rao', 'suresh@gmail.com', 'Male', 60000,
 '2021-11-19', 'Accountant', 3, 9, 'Bangalore', 'ACTIVE'),

('Ravi', 'Kumar', 'ravi@gmail.com', 'Male', 90000,
 '2018-03-21', 'Sales Manager', 4, NULL, 'Delhi', 'ACTIVE'),

('Deepak', 'Yadav', 'deepak@gmail.com', 'Male', 55000,
 '2021-05-14', 'Sales Executive', 4, 12, 'Delhi', 'ACTIVE'),

('Meena', 'Kaur', 'meena@gmail.com', 'Female', 58000,
 '2022-02-18', 'Sales Executive', 4, 12, 'Delhi', 'ACTIVE'),

('Arjun', 'Reddy', 'arjun@gmail.com', 'Male', 88000,
 '2019-10-01', 'Marketing Manager', 5, NULL, 'Hyderabad', 'ACTIVE'),

('Divya', 'Nair', 'divya@gmail.com', 'Female', 62000,
 '2021-07-15', 'Marketing Executive', 5, 15, 'Hyderabad', 'ACTIVE'),

('Manoj', 'Iyer', 'manoj@gmail.com', 'Male', 80000,
 '2019-12-05', 'Operations Manager', 6, NULL, 'Chennai', 'ACTIVE'),

('Swati', 'Mishra', 'swati@gmail.com', 'Female', 52000,
 '2022-03-20', 'Operations Executive', 6, 17, 'Chennai', 'ACTIVE'),

('Nitin', 'Bose', 'nitin@gmail.com', 'Male', 125000,
 '2016-01-10', 'Legal Head', 7, NULL, 'Mumbai', 'ACTIVE'),

('Isha', 'Malhotra', 'isha@gmail.com', 'Female', 98000,
 '2018-11-12', 'Research Lead', 8, NULL, 'Pune', 'ACTIVE'),

('Test', 'Employee', 'test@gmail.com', 'Male', 40000,
 '2024-01-10', 'Intern', NULL, NULL, 'Pune', 'ACTIVE'),

('Duplicate', 'Employee', 'amit@gmail.com', 'Male', 45000,
 '2024-02-15', 'Developer', 1, 1, 'Pune', 'ACTIVE');


-- ============================================================
-- 3. PROJECT
-- ============================================================

CREATE TABLE project (
    project_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_name VARCHAR(100),
    start_date DATE,
    end_date DATE,
    budget DECIMAL(12,2)
);


INSERT INTO project
(project_name, start_date, end_date, budget)
VALUES
('E-Commerce Platform', '2023-01-01', '2024-12-31', 500000),
('Banking Application', '2022-06-01', '2025-05-31', 800000),
('HR Management System', '2023-03-01', NULL, 300000),
('CRM System', '2024-01-01', NULL, 450000),
('Payment Gateway', '2021-01-01', '2023-12-31', 900000);


-- ============================================================
-- 4. EMPLOYEE_PROJECT
-- ============================================================

CREATE TABLE employee_project (
    employee_id INT,
    project_id INT,
    assigned_date DATE,

    PRIMARY KEY (employee_id, project_id),

    CONSTRAINT fk_employee_project_employee
        FOREIGN KEY (employee_id)
        REFERENCES employee(employee_id),

    CONSTRAINT fk_employee_project_project
        FOREIGN KEY (project_id)
        REFERENCES project(project_id)
);


INSERT INTO employee_project
(employee_id, project_id, assigned_date)
VALUES
(1, 1, '2023-01-10'),
(1, 2, '2023-02-15'),
(2, 1, '2023-01-15'),
(3, 1, '2023-02-01'),
(3, 3, '2023-03-10'),
(4, 3, '2023-04-01'),
(5, 1, '2023-05-01'),
(9, 2, '2022-06-10'),
(10, 2, '2022-07-01'),
(12, 4, '2024-01-15'),
(13, 4, '2024-02-01'),
(15, 3, '2023-03-15'),
(17, 4, '2024-01-20');


-- ============================================================
-- 5. CUSTOMER
-- ============================================================

CREATE TABLE customer (
    customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100),
    email VARCHAR(100),
    city VARCHAR(50),
    registration_date DATE
);


INSERT INTO customer
(customer_name, email, city, registration_date)
VALUES
('Raj', 'raj@gmail.com', 'Pune', '2022-01-10'),
('Asha', 'asha@gmail.com', 'Mumbai', '2022-05-15'),
('Vijay', 'vijay@gmail.com', 'Delhi', '2023-02-20'),
('Kavita', 'kavita@gmail.com', 'Hyderabad', '2023-06-10'),
('Sameer', 'sameer@gmail.com', 'Bangalore', '2024-01-05'),
('Pallavi', 'pallavi@gmail.com', 'Pune', '2024-03-15');


-- ============================================================
-- 6. PRODUCT
-- ============================================================

CREATE TABLE product (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10,2),
    stock INT
);


INSERT INTO product
(product_name, category, price, stock)
VALUES
('Laptop', 'Electronics', 75000, 20),
('Mobile', 'Electronics', 40000, 50),
('Keyboard', 'Electronics', 2000, 100),
('Mouse', 'Electronics', 1000, 150),
('Monitor', 'Electronics', 15000, 30),
('Chair', 'Furniture', 8000, 25),
('Table', 'Furniture', 12000, 15),
('Headphones', 'Electronics', 3000, 80),
('Printer', 'Electronics', 18000, 10),
('Notebook', 'Stationery', 100, 500);


-- ============================================================
-- 7. ORDERS
-- ============================================================

CREATE TABLE orders (
    order_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(12,2),
    status VARCHAR(20),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(customer_id)
);


INSERT INTO orders
(customer_id, order_date, total_amount, status)
VALUES
(1, '2024-01-10', 75000, 'COMPLETED'),
(1, '2024-02-15', 40000, 'COMPLETED'),
(2, '2024-03-20', 18000, 'COMPLETED'),
(2, '2024-04-10', 12000, 'CANCELLED'),
(3, '2024-05-05', 80000, 'COMPLETED'),
(3, '2024-06-10', 3000, 'COMPLETED'),
(4, '2024-07-15', 15000, 'COMPLETED'),
(5, '2024-08-20', 40000, 'COMPLETED'),
(1, '2024-09-01', 12000, 'COMPLETED');


-- ============================================================
-- 8. ORDER_ITEM
-- ============================================================

CREATE TABLE order_item (
    order_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT,
    product_id INT,
    quantity INT,
    price DECIMAL(10,2),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),

    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
);


INSERT INTO order_item
(order_id, product_id, quantity, price)
VALUES
(1, 1, 1, 75000),
(2, 2, 1, 40000),
(3, 9, 1, 18000),
(4, 7, 1, 12000),
(5, 6, 10, 8000),
(6, 8, 1, 3000),
(7, 5, 1, 15000),
(8, 2, 1, 40000),
(9, 7, 1, 12000);